final Map<String, String> deDE = {
  'app_title': 'Bundvarka',
  'welcome': 'Willkommen bei Bundvarka',
  'change_language': 'Sprache ändern',
  'english': 'Englisch',
  'russian': 'Russisch',
  'chats': 'Chats',
  'profile': 'Profil',
  'settings': 'Einstellungen',
  'verifying_code': 'Code wird überprüft...',
  'verification_code_is_invalid':
      'Der Bestätigungscode ist ungültig. Überprüfen Sie den Code und geben Sie den richtigen Bestätigungscode ein',
  'sending_verification_code': 'Sende einen Bestätigungscode an ',
  'saving_user_info': 'Benutzerinformationen werden gespeichert...',
  'users': 'Benutzer',
  'online': 'online',
  'last_seen': 'zuletzt gesehen',
  'ago': 'vor',
  'chat_background_updated': 'Chat-Hintergrund aktualisiert',
  'error_setting_background': 'Fehler beim Einstellen des Hintergrunds:',
  'clear_chat_history': 'Chatverlauf löschen',
  'delete_chat_confirmation':
      'Möchten Sie wirklich alle Nachrichten in diesem Chat löschen? Diese Aktion kann nicht rückgängig gemacht werden.',
  'cancel': 'ABBRECHEN',
  'delete': 'LÖSCHEN',
  'chat_history_cleared': 'Chatverlauf erfolgreich gelöscht',
  'failed_to_clear_chat': 'Fehler beim Löschen des Chatverlaufs:',
  'set_background_image': 'Hintergrundbild festlegen',
  'clear_chat_history_menu': 'Chatverlauf löschen',
  'something_went_wrong': 'Etwas ist schiefgelaufen!',
  's_video': 'Video',
  'call': 'Anruf',
  'photo_library': 'Fotogalerie',
  'profile_info': 'Profilinformationen',
  'please_provide_info':
      'Bitte geben Sie Ihren Namen und optional ein Profilfoto an',
  'next': 'WEITER',
  'username_must_be_between':
      'Der Benutzername muss zwischen 3 und 20 Zeichen lang sein',
  'profile_photo': 'Profilfoto',
  'camera': 'Kamera',
  'gallery': 'Galerie',
  'video': 'Video',
  'file': 'Datei',
  'message': 'Nachricht',
  'enter_phone_number': 'Geben Sie Ihre Telefonnummer ein',
  'verify_phone_number': 'Bestätigen Sie Ihre Telefonnummer.',
  'whats_my_number': 'Wie lautet meine Nummer?',
  'carrier_charges': 'Möglicherweise fallen Gebühren des Mobilfunkanbieters an',
  'phone_number': 'Telefonnummer',
  'search_country': 'Ländervorwahl oder Name suchen',
  'please_enter_phone_number': 'Bitte geben Sie Ihre Telefonnummer ein',
  'phone_number_too_short': 'Die Telefonnummer ist zu kurz für das Land:',
  'include_area_code':
      '\n\nGeben Sie Ihre Vorwahl an, falls Sie dies nicht getan haben',
  'phone_number_too_long':
      'Die von Ihnen eingegebene Telefonnummer ist zu lang',
  'wrong_number': 'Falsche Nummer?',
  'enter_6_digit_code': 'Geben Sie den 6-stelligen Code ein',
  'resend_code': 'Code erneut senden',
  'you_tried_to_register': 'Sie haben versucht, + zu registrieren',
  'before_requesting':
      'bevor Sie eine SMS oder einen Anruf mit Ihrem Code anfordern.',
  'no_images_in_chat': 'Keine Bilder in diesem Chat',
  'no_videos_in_chat': 'Keine Videos in diesem Chat',
  'image': 'Bild',
  'image_viewer': 'Bildbetrachter',
  'swipe_up_to_close': 'Wischen Sie nach oben, um zu schließen',
  'save': 'Speichern',
  'info': 'Info',
  'image_information': 'Bildinformationen',
  'loading_image_details': 'Lade Bilddetails...',
  'could_not_load_image_details': 'Bilddetails konnten nicht geladen werden',
  'size': 'Größe:',
  'file_size': 'Dateigröße:',
  'close': 'Schließen',
  'video_saved_to_disk': 'Video auf Datenträger gespeichert',
  'disappearing_messages': 'Verschwindende Nachrichten',
  'set_a_timer_to_delete_messages':
      'Timer zum Löschen von Nachrichten festlegen',
  'video_player_error': 'Fehler beim Laden des Videos:\n',
  'retry': 'Erneut versuchen',
  'loading_video': 'Lade Video...',
  'volume_up': 'Lautstärke erhöhen',
  'download': 'Herunterladen',
  'image_saved_to_disk_message': 'Bild auf Datenträger gespeichert',
  'uploading': 'Hochladen...',
  'recording': 'Aufnahme...',
  'error_recording_audio': 'Fehler bei der Audioaufnahme:',
  'audio_recording_not_supported':
      'Audioaufnahme wird im Web nicht unterstützt.',
  'video_size_exceeds_limit':
      'Die Videogröße überschreitet das Limit von 50 MB. Bitte wählen Sie ein kleineres Video aus.',
  'error_selecting_video': 'Fehler bei der Videoauswahl:',
  'error_selecting_image': 'Fehler bei der Bildauswahl:',
  'error_recording_video': 'Fehler bei der Videoaufnahme:',
  'error_capturing_image': 'Fehler beim Erfassen des Bildes:',
  'file_size_exceeds_limit':
      'Die Dateigröße überschreitet das Limit von 30 MB. Bitte wählen Sie eine kleinere Datei aus.',
  'error_file_null': 'Fehler: Datei ist null',
  'error_image_not_found': 'Fehler: Bild nicht gefunden',
  'error': 'Fehler',
  'no_message': 'Keine Nachricht',
  'loading_file_name': 'Lade Dateinamen...',
  'error_decrypting_file_name': 'Fehler beim Entschlüsseln des Dateinamens',
  'file_extension': 'Dateierweiterung',
  'end_to_end_encrypted':
      'Nachrichten und Anrufe sind Ende-zu-Ende-verschlüsselt. Niemand außerhalb dieses Chats, nicht einmal Bundvarka, kann sie lesen oder anhören. Tippen Sie, um mehr zu erfahren.',
  'select_contact': 'Kontakt auswählen',
  'contacts': 'Kontakt',
  'contacts_plural': 'Kontakte',
  'counting': 'Zählen',
  'search_contacts': 'Kontakte suchen...',
  'new_group': 'Neue Gruppe',
  'contacts_on_bundvarka': 'Kontakte auf Bundvarka',
  'contacts_on_phone': 'Kontakte auf dem Telefon',
  'could_not_launch_sms': 'SMS konnte nicht gestartet werden',
  'let_chat_on_bundvarka': 'Lass uns auf Bundvarka chatten!',
  's': 'e',
  'no_messages_yet': 'Noch keine Nachrichten.',
  'unknown': 'Unbekannt',
  'create_group_chat': 'Gruppenchat erstellen',
  'failed_to_pick_image': 'Fehler beim Auswählen des Bildes:',
  'group_name': 'Gruppenname',
  'select_participants': 'Teilnehmer auswählen',
  'failed_to_create_group': 'Fehler beim Erstellen der Gruppe:',
  'group_profile': 'Gruppenprofil',
  'participants': 'Teilnehmer',
  'add_participants': 'Teilnehmer hinzufügen',
  'delete_group': 'Gruppe löschen',
  'leave_group': 'Gruppe verlassen',
  'failed_to_remove_participant': 'Fehler beim Entfernen des Teilnehmers:',
  'failed_to_leave_group': 'Fehler beim Verlassen der Gruppe:',
  'failed_to_add_participants': 'Fehler beim Hinzufügen von Teilnehmern:',
  'users_list': 'Benutzerliste',
  'user_profile': 'Benutzerprofil',
  'failed_to_remove_profile_image': 'Fehler beim Entfernen des Profilbildes:',
  'user_information_updated_successfully':
      'Benutzerinformationen erfolgreich aktualisiert',
  'failed_to_update_user_information':
      'Fehler beim Aktualisieren der Benutzerinformationen:',
  'user_account_deleted_successfully': 'Benutzerkonto erfolgreich gelöscht',
  'failed_to_delete_user_account': 'Fehler beim Löschen des Benutzerkontos:',
  'username': 'Benutzername',
  'save_changes': 'Änderungen speichern',
  'delete_account': 'Konto löschen',
  'are_you_sure_you_want_to_delete_this_account':
      'Sind Sie sicher, dass Sie dieses Konto löschen möchten?',
  'no_time': 'Keine Zeit',
  'no_messages': 'Keine Nachrichten',
  'failed_to_sign_out': 'Fehler beim Abmelden:',
  'ok': 'OK',
  'please_provide_a_username': 'Bitte geben Sie einen Benutzernamen an',
  'username_must_be_between_3_and_20_characters':
      'Der Benutzername muss zwischen 3 und 20 Zeichen lang sein',
  'loading': 'Lade...',
  'are_you_sure_you_want_to_delete_your_account':
      'Sind Sie sicher, dass Sie Ihr Konto löschen möchten?',
  'sign_out': 'Abmelden',
  'are_you_sure_you_want_to_sign_out':
      'Sind Sie sicher, dass Sie sich abmelden möchten?',
  'agree_and_continue': 'Zustimmen und fortfahren',
};
