final Map<String, String> enUS = {
  'app_title': 'Bund\'varka',
  'welcome': 'Welcome to the Bund\'varka',
  'change_language': 'Change Language',
  'german': 'German',
  'chats': 'Chats',
  'profile': 'Profile',
  'settings': 'Settings',
  'users': 'Users',
  'online': 'online',
  'last_seen': 'last seen ',
  'ago': ' ago',
  'chat_background_updated': 'Chat background updated',
  'error_setting_background': 'Error setting background: ',
  'clear_chat_history': 'Clear Chat History',
  'delete_chat_confirmation':
      'Are you sure you want to delete all messages in this chat? This action cannot be undone.',
  'cancel': 'CANCEL',
  'delete': 'DELETE',
  'chat_history_cleared': 'Chat history cleared successfully',
  'failed_to_clear_chat': 'Failed to clear chat history: ',
  'set_background_image': 'Set Background Image',
  'clear_chat_history_menu': 'Clear Chat History',
  'something_went_wrong': 'Something went wrong!',
  's_video': '\'s Videos',
  'call': 'Call',
  'photo_library': 'Photo Library',
  'verifying_code':'Verifying code...',
  'verification_code_is_invalid':'Verification code is invalid. Check and enter the correct verification code',
  'sending_verification_code':'Sending a verification code to ',
  'saving_user_info':'Saving user info...',
  'profile_info': 'Profile info',
  'please_provide_info':
      'Please provide your name and an optional profile photo',
  'next': 'NEXT',
  'username_must_be_between': 'Username must be between 3 and 20 characters',
  'profile_photo': 'Profile photo',
  'camera': 'Camera',
  'gallery': 'Gallery',
  'video': 'Video',
  'file': 'File',
  'message': 'Message',
  'enter_phone_number': 'Enter your phone number',
  'verify_phone_number': 'Verify your phone number.',
  'whats_my_number': "What's my number?",
  'carrier_charges': 'Carrier charges may apply',
  'phone_number': 'phone number',
  'search_country': 'Search country code or name',
  'please_enter_phone_number': 'Please enter your phone number',
  'phone_number_too_short': 'The phone number is too short for the country: ',
  'include_area_code': '\n\nInclude your area code if you haven\'t',
  'phone_number_too_long': 'The phone number you entered is too long',
  'wrong_number': 'Wrong number?',
  'enter_6_digit_code': 'Enter 6-digit code',
  'resend_code': 'Resend code',
  'you_tried_to_register': 'You\'ve tried to register +',
  'before_requesting': ' before requesting an SMS or call with your code.',
  'no_images_in_chat': 'No images in this chat',
  'no_videos_in_chat': 'No videos in this chat',
  'image': 'Image',
  'image_viewer': 'Image Viewer',
  'swipe_up_to_close': 'Swipe up to close',
  'save': 'Save',
  'info': 'Info',
  'image_information': 'Image Information',
  'loading_image_details': 'Loading image details...',
  'could_not_load_image_details': 'Could not load image details',
  'size': 'Size: ',
  'file_size': 'File size: ',
  'close': 'Close',
  'video_saved_to_disk': 'Video saved to disk',
  'disappearing_messages': 'Disappearing messages',
  'set_a_timer_to_delete_messages': 'Set a timer to delete messages',
  'video_player_error': 'Failed to load video:\n',
  'retry': 'Retry',
  'loading_video': 'Loading video...',
  'volume_up': 'Volume up',
  'download': 'Download',
  'image_saved_to_disk_message': 'Image saved to disk',
  'uploading': 'Uploading...',
  'recording': 'Recording...',
  'error_recording_audio': 'Error recording audio: ',
  'audio_recording_not_supported': 'Audio recording is not supported on web.',
  'video_size_exceeds_limit':
      'Video size exceeds 50MB limit. Please select a smaller video.',
  'error_selecting_video': 'Error selecting video: ',
  'error_selecting_image': 'Error selecting image: ',
  'error_recording_video': 'Error recording video: ',
  'error_capturing_image': 'Error capturing image: ',
  'file_size_exceeds_limit':
      'File size exceeds 30MB limit. Please select a smaller file.',
  'error_file_null': 'Error: File is null',
  'error_image_not_found': 'Error: Image file not found',
  'error': 'Error',
  'no_message': 'No message',
  'loading_file_name': 'Loading file name...',
  'error_decrypting_file_name': 'Error decrypting file name',
  'file_extension': 'File extension',
  'end_to_end_encrypted':
      'Message and calls are end-to-end encrypted. No one outside of this chat, not even Bund\'varka, can read or listen to them. Tap to learn more.',
  'select_contact': 'Select contact',
  'contacts': 'Contact',
  'contacts_plural': 'Contacts',
  'counting': 'Counting',
  'search_contacts': 'Search contacts...',
  'new_group': 'New group',
  'contacts_on_bundvarka': 'Contacts on Bund\'varka',
  'contacts_on_phone': 'Contacts on Phone',
  'could_not_launch_sms': 'Could not launch SMS',
  'let_chat_on_bundvarka': "Let's chat on Bundvarka!",
  's': 's',
  'no_messages_yet': 'No messages yet.',
  'unknown': 'Unknown',
  'create_group_chat': 'Create Group Chat',
  'failed_to_pick_image': 'Failed to pick image: ',
  'group_name': 'Group Name',
  'select_participants': 'Select Participants',
  'failed_to_create_group': 'Failed to create group: ',
  'group_profile': 'Group Profile',
  'participants': 'Participants',
  'add_participants': 'Add Participants',
  'delete_group': 'Delete Group',
  'leave_group': 'Leave Group',
  'failed_to_remove_participant': 'Failed to remove participant: ',
  'failed_to_leave_group': 'Failed to leave group: ',
  'failed_to_add_participants': 'Failed to add participants: ',
  'users_list': 'Users List',
  'user_profile': 'User Profile',
  'failed_to_remove_profile_image': 'Failed to remove profile image: ',
  'user_information_updated_successfully':
      'User information updated successfully',
  'failed_to_update_user_information': 'Failed to update user information: ',
  'user_account_deleted_successfully': 'User account deleted successfully',
  'failed_to_delete_user_account': 'Failed to delete user account: ',
  'username': 'Username',
  'save_changes': 'Save Changes',
  'delete_account': 'Delete Account',
  'are_you_sure_you_want_to_delete_this_account':
      'Are you sure you want to delete this account?',
  'no_time': 'No time',
  'no_messages': 'No messages',
  'failed_to_sign_out': 'Failed to sign out: ',
  'ok': 'OK',
  'please_provide_a_username': 'Please, provide a username',
  'username_must_be_between_3_and_20_characters':
      'Username must be between 3 and 20 characters',
  'loading': 'Loading...',
  'are_you_sure_you_want_to_delete_your_account':
      'Are you sure you want to delete your account?',
  'sign_out': 'Sign Out',
  'are_you_sure_you_want_to_sign_out': 'Are you sure you want to sign out?',
  'agree_and_continue': 'Agree and Continue',
};
