final Map<String, String> ruRU = {
  'app_title': 'Бундъварка',
  'welcome': 'Добро пожаловать в Бундъварка',
  'change_language': 'Сменить язык',
  'chats': 'Чаты',
  'profile': 'Профиль',
  'settings': 'Настройки',
  'users': 'Пользователи',
  'online': 'онлайн',
  'last_seen': 'был(а) в сети',
  'ago': 'назад',
  'chat_background_updated': 'Фон чата обновлен',
  'error_setting_background': 'Ошибка установки фона:',
  'clear_chat_history': 'Очистить историю чата',
  'verifying_code': 'Проверка кода...',
  'verification_code_is_invalid':
      'Код подтверждения недействителен. Проверьте и введите правильный код подтверждения',
  'sending_verification_code': 'Отправка кода подтверждения на ',
  'saving_user_info': 'Сохранение информации о пользователе...',
  'delete_chat_confirmation':
      'Вы уверены, что хотите удалить все сообщения в этом чате? Это действие нельзя отменить.',
  'cancel': 'ОТМЕНА',
  'delete': 'УДАЛИТЬ',
  'chat_history_cleared': 'История чата успешно очищена',
  'failed_to_clear_chat': 'Не удалось очистить историю чата:',
  'set_background_image': 'Установить фоновое изображение',
  'clear_chat_history_menu': 'Очистить историю чата',
  'something_went_wrong': 'Что-то пошло не так!',
  's_video': 'видео',
  'call': 'Звонок',
  'photo_library': 'Фотогалерея',
  'profile_info': 'Информация профиля',
  'please_provide_info':
      'Пожалуйста, укажите ваше имя и, при желании, фото профиля',
  'next': 'ДАЛЕЕ',
  'username_must_be_between':
      'Имя пользователя должно содержать от 3 до 20 символов',
  'profile_photo': 'Фото профиля',
  'camera': 'Камера',
  'gallery': 'Галерея',
  'video': 'Видео',
  'file': 'Файл',
  'message': 'Сообщение',
  'enter_phone_number': 'Введите ваш номер телефона',
  'verify_phone_number': 'Подтвердите ваш номер телефона.',
  'whats_my_number': 'Какой мой номер?',
  'carrier_charges': 'Могут применяться тарифы оператора',
  'phone_number': 'номер телефона',
  'search_country': 'Поиск кода или названия страны',
  'please_enter_phone_number': 'Пожалуйста, введите ваш номер телефона',
  'phone_number_too_short': 'Номер телефона слишком короткий для этой страны:',
  'include_area_code': '\n\nУкажите код региона, если вы этого не сделали',
  'phone_number_too_long': 'Введенный вами номер телефона слишком длинный',
  'wrong_number': 'Неправильный номер?',
  'enter_6_digit_code': 'Введите 6-значный код',
  'resend_code': 'Отправить код повторно',
  'you_tried_to_register': 'Вы пытались зарегистрировать +',
  'before_requesting': 'перед запросом SMS или звонка с вашим кодом.',
  'no_images_in_chat': 'В этом чате нет изображений',
  'no_videos_in_chat': 'В этом чате нет видео',
  'image': 'Изображение',
  'image_viewer': 'Просмотр изображений',
  'swipe_up_to_close': 'Проведите вверх, чтобы закрыть',
  'save': 'Сохранить',
  'info': 'Информация',
  'image_information': 'Информация об изображении',
  'loading_image_details': 'Загрузка деталей изображения...',
  'could_not_load_image_details': 'Не удалось загрузить детали изображения',
  'size': 'Размер:',
  'file_size': 'Размер файла:',
  'close': 'Закрыть',
  'video_saved_to_disk': 'Видео сохранено на диск',
  'disappearing_messages': 'Исчезающие сообщения',
  'set_a_timer_to_delete_messages': 'Установите таймер для удаления сообщений',
  'video_player_error': 'Не удалось загрузить видео:\n',
  'retry': 'Повторить',
  'loading_video': 'Загрузка видео...',
  'volume_up': 'Громкость',
  'download': 'Скачать',
  'image_saved_to_disk_message': 'Изображение сохранено на диск',
  'uploading': 'Загрузка...',
  'recording': 'Запись...',
  'error_recording_audio': 'Ошибка записи аудио:',
  'audio_recording_not_supported':
      'Запись аудио не поддерживается в веб-версии.',
  'video_size_exceeds_limit':
      'Размер видео превышает лимит 50 МБ. Пожалуйста, выберите видео меньшего размера.',
  'error_selecting_video': 'Ошибка выбора видео:',
  'error_selecting_image': 'Ошибка выбора изображения:',
  'error_recording_video': 'Ошибка записи видео:',
  'error_capturing_image': 'Ошибка захвата изображения:',
  'file_size_exceeds_limit':
      'Размер файла превышает лимит 30 МБ. Пожалуйста, выберите файл меньшего размера.',
  'error_file_null': 'Ошибка: Файл пуст',
  'error_image_not_found': 'Ошибка: Изображение не найдено',
  'error': 'Ошибка',
  'no_message': 'Нет сообщения',
  'loading_file_name': 'Загрузка имени файла...',
  'error_decrypting_file_name': 'Ошибка расшифровки имени файла',
  'file_extension': 'Расширение файла',
  'end_to_end_encrypted':
      'Сообщения и звонки зашифрованы от начала до конца. Никто за пределами этого чата, даже Бундъварка, не может их прочитать или прослушать. Нажмите, чтобы узнать больше.',
  'select_contact': 'Выберите контакт',
  'contacts': 'Контакт',
  'contacts_plural': 'Контакты',
  'counting': 'Подсчет',
  'search_contacts': 'Поиск контактов...',
  'new_group': 'Новая группа',
  'contacts_on_bundvarka': 'Контакты в Бундъварка',
  'contacts_on_phone': 'Контакты на телефоне',
  'could_not_launch_sms': 'Не удалось открыть SMS',
  'let_chat_on_bundvarka': 'Давайте пообщаемся в Бундъварка!',
  's': 'ы',
  'no_messages_yet': 'Пока нет сообщений.',
  'unknown': 'Неизвестно',
  'create_group_chat': 'Создать групповой чат',
  'failed_to_pick_image': 'Не удалось выбрать изображение:',
  'group_name': 'Название группы',
  'select_participants': 'Выберите участников',
  'failed_to_create_group': 'Не удалось создать группу:',
  'group_profile': 'Профиль группы',
  'participants': 'Участники',
  'add_participants': 'Добавить участников',
  'delete_group': 'Удалить группу',
  'leave_group': 'Покинуть группу',
  'failed_to_remove_participant': 'Не удалось удалить участника:',
  'failed_to_leave_group': 'Не удалось покинуть группу:',
  'failed_to_add_participants': 'Не удалось добавить участников:',
  'users_list': 'Список пользователей',
  'user_profile': 'Профиль пользователя',
  'failed_to_remove_profile_image': 'Не удалось удалить изображение профиля:',
  'user_information_updated_successfully':
      'Информация о пользователе успешно обновлена',
  'failed_to_update_user_information':
      'Не удалось обновить информацию о пользователе:',
  'user_account_deleted_successfully': 'Аккаунт пользователя успешно удален',
  'failed_to_delete_user_account': 'Не удалось удалить аккаунт пользователя:',
  'username': 'Имя пользователя',
  'save_changes': 'Сохранить изменения',
  'delete_account': 'Удалить аккаунт',
  'are_you_sure_you_want_to_delete_this_account':
      'Вы уверены, что хотите удалить этот аккаунт?',
  'no_time': 'Нет времени',
  'no_messages': 'Нет сообщений',
  'failed_to_sign_out': 'Не удалось выйти:',
  'ok': 'ОК',
  'please_provide_a_username': 'Пожалуйста, укажите имя пользователя',
  'username_must_be_between_3_and_20_characters':
      'Имя пользователя должно содержать от 3 до 20 символов',
  'loading': 'Загрузка...',
  'are_you_sure_you_want_to_delete_your_account':
      'Вы уверены, что хотите удалить свой аккаунт?',
  'sign_out': 'Выйти',
  'are_you_sure_you_want_to_sign_out': 'Вы уверены, что хотите выйти?',
  'agree_and_continue': 'Согласиться и продолжить',
};
